[package]
name = "hackrschat-client"

# Inherit from root's Cargo.toml
rust-version.workspace = true
edition.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true


[dependencies]
hackrschat-common = { path = "../hackrschat-common" }
cursive = "0.21"
serde_json = "1.0"
