[package]
name = "hackrschat-server"

# Inherit from root's Cargo.toml
rust-version.workspace = true
edition.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true


[dependencies]
hackrschat-common = { path = "../hackrschat-common", features = ["sqlx"] }
anyhow = "1.0.86"
dotenvy = "0.15"
rcgen = "0.13.1"
rustls = "0.23.12"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.8", features = [
  "postgres",
  "runtime-tokio",
  "time",
  "chrono",
  "migrate",
] }
time = { version = "0.3.36", features = ["serde"] }
tokio = { version = "1.39.3", features = [
  # "full",
  "io-util",
  "macros",
  "net",
  "rt",
  "rt-multi-thread",
] }
tokio-rustls = "0.26.0"

